[package]
name = "ra-mir-export"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
ra-mir-types = { path = "../crates/ra-mir-types" }
postcard = { version = "1.1.3", features = ["alloc"] }
