[package]
name = "ra-mir-export"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
postcard = { version = "1.1.3", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
